[colors]
ansi = [
  "#AF3029",
  "#C55D17",
  "#B38F00",
  "#0F7E32",
  "#1B9E97",
  "#0060F1",
  "#7D00CC",
  "#C31562"
]
brights = [
  "#D14D41",
  "#F27F35",
  "#E5B800",
  "#00CA51",
  "#4CC0BA",
  "#47A8FF",
  "#C372FC",
  "#FF4C8D"
]
foreground = "#171717"
background = "#FFFFFF"
cursor_bg = "#171717"
cursor_border = "#171717"
cursor_fg = "#FFFFFF"
selection_bg = "#BDBDBD"
selection_fg = "#171717"
[colors.indexed]
