import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  experimental: {
    optimizePackageImports: [
      "lucide-react",
      "@radix-ui/react-icons",
      "@radix-ui/react-select",
      "@radix-ui/react-dialog",
      "@radix-ui/react-dropdown-menu",
      "@radix-ui/react-popover",
      "@radix-ui/react-tabs",
      "@radix-ui/react-tooltip",
      "@radix-ui/react-slot",
      "@radix-ui/react-checkbox",
      "@radix-ui/react-switch",
      "@radix-ui/react-slider",
      "@radix-ui/react-accordion",
      "@radix-ui/react-scroll-area",
      "culori",
      "date-fns",
      "shiki",
      "@shikijs/monaco",
    ],
  },

  async rewrites() {
    return [
      {
        source: "/ingest/static/:path*",
        destination: "https://us-assets.i.posthog.com/static/:path*",
      },
      {
        source: "/ingest/:path*",
        destination: "https://us.i.posthog.com/:path*",
      },
      // tinte's own design system, served as a fetchable artifact (llms.txt
      // style). Generated by `bun run generate:design` at the repo root.
      {
        source: "/design.md",
        destination: "/design/design.md",
      },
      {
        source: "/tokens.css",
        destination: "/design/tokens.css",
      },
    ];
  },

  async headers() {
    return [
      {
        source: "/design.md",
        headers: [
          { key: "Content-Type", value: "text/markdown; charset=utf-8" },
        ],
      },
      {
        source: "/plugin/skills/:skill/SKILL.md",
        headers: [
          { key: "Content-Type", value: "text/markdown; charset=utf-8" },
        ],
      },
    ];
  },

  // This is required to support PostHog trailing slash API requests
  skipTrailingSlashRedirect: true,

  async redirects() {
    return [
      {
        source: "/shadcn",
        destination: "/",
        permanent: true,
      },
      {
        source: "/vscode",
        destination: "/",
        permanent: true,
      },
      // The theme workbench moved under /legacy. These keep bookmarks and
      // indexed URLs alive. "/" is deliberately absent: it is the new home.
      //
      // Machine routes are NOT redirected and must stay where they are:
      // /api/* (CLI installer + shadcn preset), /r/* (shadcn registry), and
      // /themes/:slug.json (public theme JSON). The :slug exclusion below is
      // what keeps that last one reachable.
      {
        source: "/workbench",
        destination: "/legacy/workbench",
        permanent: true,
      },
      {
        source: "/workbench/:path*",
        destination: "/legacy/workbench/:path*",
        permanent: true,
      },
      {
        source: "/themes",
        destination: "/legacy/themes",
        permanent: true,
      },
      {
        source: "/themes/:slug((?!.*\\.json$).*)",
        destination: "/legacy/themes/:slug",
        permanent: true,
      },
    ];
  },

  turbopack: {
    rules: {
      "*.md": {
        loaders: ["raw-loader"],
        as: "*.js",
      },
    },
  },

  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "images.unsplash.com",
      },
      {
        protocol: "https",
        hostname: "img.clerk.com",
      },
    ],
  },
};

export default nextConfig;
