[build]
  publish = "dist"
  command = "bun run build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/api/generate-vscode-theme"
  to = "/.netlify/functions/generate-vscode-theme"
  status = 200
