[build]
  command = "echo 'No build needed for functions only'"
  publish = "public"

[context.production.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
