import { ThemeConfig } from "./types";

export const defaultThemeConfig: ThemeConfig = {
  name: "one-hunter",
  displayName: "One Hunter",
  type: "dark",
  palette: {
    text: "#E3E1E1",
    "text-2": "#A3A3A3",
    "text-3": "#8F8F8F",
    interface: "#35373A",
    "interface-2": "#3E4043",
    "interface-3": "#47494D",
    background: "#1D2127",
    "background-2": "#2C2E31",
    primary: "#F06293",
    secondary: "#E3E1E1",
    accent: "#50C2F7",
    "accent-2": "#66DFC4",
    "accent-3": "#F7BC62",
  },
  tokenColors: {
    plain: "text",
    classes: "accent",
    interfaces: "accent",
    structs: "accent",
    enums: "accent",
    keys: "text",
    methods: "secondary",
    functions: "accent",
    variables: "text",
    variablesOther: "secondary",
    globalVariables: "accent-2",
    localVariables: "text",
    parameters: "text",
    properties: "text",
    strings: "accent-2",
    stringEscapeSequences: "text",
    keywords: "primary",
    keywordsControl: "primary",
    storageModifiers: "primary",
    comments: "text",
    docComments: "text",
    numbers: "accent-3",
    booleans: "accent-3",
    operators: "primary",
    macros: "secondary",
    preprocessor: "accent-2",
    urls: "secondary",
    tags: "accent-2",
    jsxTags: "secondary",
    attributes: "accent",
    types: "secondary",
    constants: "secondary",
    labels: "accent-2",
    namespaces: "accent",
    modules: "primary",
    typeParameters: "accent",
    exceptions: "primary",
    decorators: "accent",
    calls: "text",
    punctuation: "text",
  },
};
