import { WarpPreview } from "@/components/preview/warp/warp-preview";
import { WarpIcon } from "@/components/shared/icons";
import type { TinteTheme } from "@tinte/core";
import {
  createPolineColorMapping,
  getDisplayName,
  getThemeName,
  toYAML,
} from "./poline-base";
import type { PreviewableProvider, ProviderOutput } from "./types";

export interface WarpTheme {
  accent: string;
  background: string;
  details: "darker" | "lighter";
  foreground: string;
  terminal_colors: {
    bright: {
      black: string;
      blue: string;
      cyan: string;
      green: string;
      magenta: string;
      red: string;
      white: string;
      yellow: string;
    };
    normal: {
      black: string;
      blue: string;
      cyan: string;
      green: string;
      magenta: string;
      red: string;
      white: string;
      yellow: string;
    };
  };
}

function generateWarpTheme(
  theme: TinteTheme,
  mode: "light" | "dark",
): WarpTheme {
  const block = theme[mode];
  const colorMapping = createPolineColorMapping(block);

  // Use opposite mode for contrast colors
  const oppositeBlock = theme[mode === "light" ? "dark" : "light"];
  const oppositeMapping = createPolineColorMapping(oppositeBlock);

  return {
    accent: colorMapping.accent,
    background: colorMapping.bg,
    details: mode === "light" ? "lighter" : "darker",
    foreground: colorMapping.tx,
    terminal_colors: {
      bright: {
        black: colorMapping.tx2,
        blue: colorMapping.blue,
        cyan: colorMapping.cyan,
        green: colorMapping.green,
        magenta: colorMapping.magenta,
        red: colorMapping.red,
        white: oppositeMapping.bg,
        yellow: colorMapping.yellow,
      },
      normal: {
        black: oppositeMapping.bg,
        blue: colorMapping.blue2,
        cyan: colorMapping.cyan2,
        green: colorMapping.green2,
        magenta: colorMapping.magenta2,
        red: colorMapping.red2,
        white: colorMapping.tx,
        yellow: colorMapping.yellow2,
      },
    },
  };
}

export const warpProvider: PreviewableProvider<{
  light: WarpTheme;
  dark: WarpTheme;
}> = {
  metadata: {
    id: "warp",
    name: "Warp",
    description: "Modern terminal with AI and collaboration features",
    category: "terminal",
    tags: ["terminal", "ai", "modern", "collaboration"],
    icon: WarpIcon,
    website: "https://www.warp.dev/",
    documentation: "https://docs.warp.dev/appearance/custom-themes",
  },

  fileExtension: "yaml",
  mimeType: "application/x-yaml",

  convert: (theme: TinteTheme) => ({
    light: generateWarpTheme(theme, "light"),
    dark: generateWarpTheme(theme, "dark"),
  }),

  export: (theme: TinteTheme, filename?: string): ProviderOutput => {
    const converted = warpProvider.convert(theme);
    const themeName = filename || getThemeName("tinte-theme");

    // Use dark theme by default
    const warpTheme = converted.dark;

    // Add metadata to the theme
    const _themeWithMetadata = {
      // Metadata (as YAML comments would be ideal, but we'll use a structure that works)
      name: getDisplayName("Tinte Theme"),
      generator: "Tinte Theme Converter with Poline",
      url: "https://github.com/your-repo/tinte",

      // Theme data
      ...warpTheme,
    };

    const yamlContent = `# Warp Terminal Theme
# Theme: ${getDisplayName("Tinte Theme")}
# Generated by: Tinte Theme Converter with Poline
# URL: https://github.com/your-repo/tinte

${toYAML(warpTheme)}`;

    return {
      content: yamlContent,
      filename: `${themeName}-warp.yaml`,
      mimeType: warpProvider.mimeType,
    };
  },

  validate: (output: { light: WarpTheme; dark: WarpTheme }) => {
    const validateTheme = (theme: WarpTheme) =>
      !!(
        theme.accent &&
        theme.background &&
        theme.foreground &&
        theme.details &&
        theme.terminal_colors?.bright?.red &&
        theme.terminal_colors?.bright?.green &&
        theme.terminal_colors?.bright?.blue &&
        theme.terminal_colors?.normal?.red &&
        theme.terminal_colors?.normal?.green &&
        theme.terminal_colors?.normal?.blue
      );

    return validateTheme(output.light) && validateTheme(output.dark);
  },

  preview: {
    component: WarpPreview,
  },
};
