import {
  AlacrittyIcon,
  BananaIcon,
  CursorIcon,
  GhosttyIcon,
  GIMPIcon,
  JetBrainsIcon,
  KittyIcon,
  NeovimIcon,
  ObsidianIcon,
  ReplitIcon,
  ShadcnIcon,
  ShikiIcon,
  SlackIcon,
  VSCodeIcon,
  WarpIcon,
  WindowsTerminalIcon,
  ZedIcon,
} from "@/components/shared/icons";

export const ALL_PROVIDERS = [
  "shadcn/ui",
  "VS Code",
  "Cursor",
  "Shiki",
  "Zed",
  "Warp",
  "Alacritty",
  "Windows Terminal",
  "Kitty",
  "Ghostty",
  "JetBrains",
  "Slack",
  "Replit",
  "Neovim",
  "Obsidian",
  "GIMP",
] as const;

export type Provider = (typeof ALL_PROVIDERS)[number];

export const PROVIDER_ICONS: Record<
  Provider,
  React.ComponentType<{ className?: string }>
> = {
  "shadcn/ui": ShadcnIcon,
  Cursor: CursorIcon,
  "VS Code": VSCodeIcon,
  Shiki: ShikiIcon,
  Zed: ZedIcon,
  Warp: WarpIcon,
  Alacritty: AlacrittyIcon,
  "Windows Terminal": WindowsTerminalIcon,
  Kitty: KittyIcon,
  Ghostty: GhosttyIcon,
  JetBrains: JetBrainsIcon,
  Slack: SlackIcon,
  Replit: ReplitIcon,
  Neovim: NeovimIcon,
  Obsidian: ObsidianIcon,
  GIMP: GIMPIcon,
};

export const ALL_FORMATTED_PROVIDERS = [
  { id: "shadcn", name: "shadcn/ui", icon: ShadcnIcon },
  { id: "vscode", name: "VS Code", icon: VSCodeIcon },
  { id: "shiki", name: "Shiki", icon: ShikiIcon, category: "editor" },
  { id: "banana", name: "Nano Banana", icon: BananaIcon, category: "other" },
  { id: "zed", name: "Zed", icon: ZedIcon, category: "editor" },
  { id: "warp", name: "Warp", icon: WarpIcon, category: "terminal" },
  {
    id: "alacritty",
    name: "Alacritty",
    icon: AlacrittyIcon,
    category: "terminal",
  },
  { id: "slack", name: "Slack", icon: SlackIcon, category: "other" },
  { id: "kitty", name: "Kitty", icon: KittyIcon, category: "terminal" },
  { id: "ghostty", name: "Ghostty", icon: GhosttyIcon, category: "terminal" },
  { id: "obsidian", name: "Obsidian", icon: ObsidianIcon, category: "other" },
  {
    id: "windows-terminal",
    name: "Windows Terminal",
    icon: WindowsTerminalIcon,
    category: "terminal",
  },
  {
    id: "jetbrains",
    name: "JetBrains",
    icon: JetBrainsIcon,
    category: "editor",
  },
  { id: "replit", name: "Replit", icon: ReplitIcon, category: "editor" },
  { id: "neovim", name: "Neovim", icon: NeovimIcon, category: "editor" },
  { id: "cursor", name: "Cursor", icon: CursorIcon, category: "editor" },
  { id: "gimp", name: "GIMP", icon: GIMPIcon, category: "design" },
];
