import { rgbToHex } from "@uiw/color-convert";
import type { GIMPPalette } from "@/lib/providers/gimp";
import { useThemeContext } from "@/providers/theme";

interface GimpPreviewProps {
  theme: { light: GIMPPalette; dark: GIMPPalette };
  className?: string;
}

export function GimpPreview({ theme, className }: GimpPreviewProps) {
  const { currentMode } = useThemeContext();
  const currentPalette = currentMode === "dark" ? theme.dark : theme.light;

  // GIMP palette preview showing color swatches
  return (
    <div
      className={`rounded-lg border overflow-hidden bg-card ${className || ""}`}
    >
      {/* GIMP header */}
      <div className="px-4 py-3 border-b bg-muted flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="text-sm font-medium text-foreground">
            GIMP Palette
          </div>
        </div>
        <div className="text-xs text-muted-foreground">
          {currentPalette.colors.length} colors • {currentMode} mode
        </div>
      </div>

      {/* Palette grid */}
      <div className="p-4">
        <div className="grid grid-cols-8 gap-2 mb-4">
          {currentPalette.colors.map((color, index) => {
            const hex = rgbToHex({
              r: color.red,
              g: color.green,
              b: color.blue,
            });
            return (
              <div
                key={index}
                className="aspect-square rounded border border-border cursor-pointer hover:scale-110 transition-transform"
                style={{ backgroundColor: hex }}
                title={`${color.name}: ${hex}`}
              />
            );
          })}
        </div>

        {/* Palette info */}
        <div className="bg-background rounded border p-3 text-xs font-mono">
          <div className="text-foreground mb-2"># GIMP Palette</div>
          <div className="text-muted-foreground mb-2">
            # Name: {currentPalette.name}
          </div>
          <div className="text-muted-foreground mb-2">
            # Generated by Tinte Theme Converter
          </div>
          <div className="space-y-1">
            {currentPalette.colors.slice(0, 6).map((color, index) => (
              <div key={index} className="text-foreground">
                {color.red.toString().padStart(3)}{" "}
                {color.green.toString().padStart(3)}{" "}
                {color.blue.toString().padStart(3)} {color.name}
              </div>
            ))}
            {currentPalette.colors.length > 6 && (
              <div className="text-muted-foreground">
                ... and {currentPalette.colors.length - 6} more colors
              </div>
            )}
          </div>
        </div>
      </div>

      {/* GIMP tools simulation */}
      <div className="border-t bg-muted/50 p-3">
        <div className="flex items-center justify-center gap-4 text-xs text-muted-foreground">
          <div className="flex items-center gap-1">
            <div className="w-4 h-4 bg-muted-foreground/30 rounded"></div>
            <span>Brush</span>
          </div>
          <div className="flex items-center gap-1">
            <div className="w-4 h-4 bg-muted-foreground/30 rounded"></div>
            <span>Pencil</span>
          </div>
          <div className="flex items-center gap-1">
            <div className="w-4 h-4 bg-muted-foreground/30 rounded"></div>
            <span>Fill</span>
          </div>
          <div className="flex items-center gap-1">
            <div
              className="w-4 h-4 rounded border-2 border-border"
              style={{
                backgroundColor: currentPalette.colors[0]
                  ? rgbToHex({
                      r: currentPalette.colors[0].red,
                      g: currentPalette.colors[0].green,
                      b: currentPalette.colors[0].blue,
                    })
                  : "#000000",
              }}
            ></div>
            <span>FG</span>
          </div>
          <div className="flex items-center gap-1">
            <div
              className="w-4 h-4 rounded border-2 border-border"
              style={{
                backgroundColor: currentPalette.colors[1]
                  ? rgbToHex({
                      r: currentPalette.colors[1].red,
                      g: currentPalette.colors[1].green,
                      b: currentPalette.colors[1].blue,
                    })
                  : "#ffffff",
              }}
            ></div>
            <span>BG</span>
          </div>
        </div>
      </div>
    </div>
  );
}
