import type { VSCodePalette } from "@/db/schema";

const tokenScopeMap = {
  interfaces: ["entity.name.type.interface", "entity.name.type"],
  structs: ["entity.name.type.struct"],
  enums: ["entity.name.type.enum"],
  keys: ["meta.object-literal.key"],
  methods: ["entity.name.function.method", "meta.function.method"],
  functions: [
    "entity.name.function",
    "support.function",
    "meta.function-call.generic",
  ],
  variables: [
    "variable",
    "meta.variable",
    "variable.other.object.property",
    "variable.other.readwrite.alias",
  ],
  variablesOther: ["variable.other.object"],
  globalVariables: ["variable.other.global", "variable.language.this"],
  localVariables: ["variable.other.local"],
  parameters: ["variable.parameter", "meta.parameter"],
  properties: ["variable.other.property", "meta.property"],
  strings: ["string", "string.other.link", "markup.inline.raw.string.markdown"],
  stringEscapeSequences: [
    "constant.character.escape",
    "constant.other.placeholder",
  ],
  keywords: ["keyword"],
  keywordsControl: [
    "keyword.control.import",
    "keyword.control.from",
    "keywaord.import",
  ],
  storageModifiers: ["storage.modifier", "keyword.modifier", "storage.type"],
  comments: ["comment", "punctuation.definition.comment"],
  docComments: ["comment.documentation", "comment.line.documentation"],
  numbers: ["constant.numeric"],
  booleans: ["constant.language.boolean", "constant.language.json"],
  operators: ["keyword.operator"],
  macros: ["entity.name.function.preprocessor", "meta.preprocessor"],
  preprocessor: ["meta.preprocessor"],
  urls: ["markup.underline.link"],
  tags: ["entity.name.tag"],
  jsxTags: ["support.class.component"],
  attributes: ["entity.other.attribute-name", "meta.attribute"],
  types: ["support.type"],
  constants: ["variable.other.constant", "variable.readonly"],
  labels: ["entity.name.label", "punctuation.definition.label"],
  namespaces: [
    "entity.name.namespace",
    "storage.modifier.namespace",
    "markup.bold.markdown",
  ],
  modules: ["entity.name.module", "storage.modifier.module"],
  typeParameters: ["variable.type.parameter", "variable.parameter.type"],
  exceptions: ["keyword.control.exception", "keyword.control.trycatch"],
  decorators: [
    "meta.decorator",
    "punctuation.decorator",
    "entity.name.function.decorator",
  ],
  calls: ["variable.function"],
  punctuation: [
    "punctuation",
    "punctuation.terminator",
    "punctuation.definition.tag",
    "punctuation.separator",
    "punctuation.definition.string",
    "punctuation.section.block",
  ],
  plain: ["source", "support.type.property-name.css"],
};

const tokenColorMap = {
  plain: "text",
  classes: "accent",
  interfaces: "accent",
  structs: "accent",
  enums: "accent",
  keys: "text",
  methods: "secondary",
  functions: "accent",
  variables: "text",
  variables_other: "secondary",
  global_variables: "accent-2",
  local_variables: "text",
  parameters: "text",
  properties: "text",
  strings: "accent-2",
  string_escape_sequences: "text",
  keywords: "primary",
  keywords_control: "primary",
  storage_modifiers: "primary",
  comments: "text-3",
  doc_comments: "text-3",
  numbers: "accent-3",
  booleans: "accent-3",
  operators: "primary",
  macros: "secondary",
  preprocessor: "accent-2",
  urls: "secondary",
  tags: "primary",
  jsx_tags: "secondary",
  attributes: "accent",
  types: "secondary",
  constants: "secondary",
  labels: "accent-2",
  namespaces: "accent",
  modules: "primary",
  type_parameters: "accent",
  exceptions: "primary",
  decorators: "accent",
  calls: "text",
  punctuation: "text",
};

export function getVSCodeTokenColors(palette: VSCodePalette) {
  return Object.entries(tokenColorMap).map(([token, colorKey]) => ({
    name: token,
    scope: tokenScopeMap[token as keyof typeof tokenScopeMap],
    settings: {
      foreground: palette[colorKey as keyof typeof palette],
    },
  }));
}
