import type { TokenColorMap } from "@/lib/providers/vscode";

export const defaultTokenColorMap: TokenColorMap = {
  plain: "tx",
  punctuation: "tx_2",
  classes: "pr",
  interfaces: "pr",
  structs: "pr",
  enums: "pr",
  types: "sc",
  typeParameters: "pr",
  functions: "pr",
  methods: "sc",
  calls: "tx",
  variables: "tx",
  variablesOther: "tx",
  globalVariables: "ac_2",
  localVariables: "tx",
  parameters: "tx",
  properties: "tx",
  keys: "tx",
  keywords: "sc",
  keywordsControl: "sc",
  storageModifiers: "sc",
  operators: "sc",
  strings: "ac_2",
  stringEscapeSequences: "tx",
  numbers: "ac_3",
  booleans: "ac_3",
  constants: "tx",
  comments: "tx_3",
  docComments: "tx_3",
  tags: "sc",
  jsxTags: "sc",
  attributes: "pr",
  urls: "sc",
  namespaces: "pr",
  modules: "sc",
  macros: "sc",
  preprocessor: "ac_2",
  exceptions: "sc",
  decorators: "pr",
  labels: "ac_2",
};
